### ISSUE TITLE
livestorm create is failing

### ISSUE THREAD

**Issue by pranjalrajput** [livestorm/livestorm-plugins-examples#8]
my node version is v12.22.12

the `livestorm create` command is failing with following output

```
/Users/pr/.config/yarn/global/node_modules/@livestorm/cli/src/helpers/getLivestormConfig.js:49
    let envConfig = environments?.[envName]
                                 ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/pr/.config/yarn/global/node_modules/@livestorm/cli/src/cmds/publish.js:4:28)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by pranjalrajput** [comment]
this seems to have resolved when i tried on a different workstation. 
please feel free to close/delete this.

**Comment by pranjalrajput** [comment]
Actually this is the error on a fresh install of OS and node.
I ran the commands on fresh docker image.
`yarn build`

```
Error: Command failed: yarn build
/livestorm-plugin-investmentor-interactive/node_modules/loader-runner/lib/LoaderRunner.js:146
                if(isError) throw e;
                            ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at BulkUpdateDecorator.hashFactory (/livestorm-plugin-investmentor-interactive/node_modules/webpack/lib/util/createHash.js:138:18)
    at BulkUpdateDecorator.update (/livestorm-plugin-investmentor-interactive/node_modules/webpack/lib/util/createHash.js:44:50)
    at RawSource.updateHash (/livestorm-plugin-investmentor-interactive/node_modules/webpack-sources/lib/RawSource.js:64:8)
    at NormalModule._initBuildHash (/livestorm-plugin-investmentor-interactive/node_modules/webpack/lib/NormalModule.js:752:17)
    at handleParseResult (/livestorm-plugin-investmentor-interactive/node_modules/webpack/lib/NormalModule.js:816:10)
    at /livestorm-plugin-investmentor-interactive/node_modules/webpack/lib/NormalModule.js:907:4
    at processResult (/livestorm-plugin-investmentor-interactive/node_modules/webpack/lib/NormalModule.js:639:11)
    at /livestorm-plugin-investmentor-interactive/node_modules/webpack/lib/NormalModule.js:691:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.5.1
error Command failed with exit code 1.

```

**Comment by pranjalrajput** [comment]
this seems to fix this for me 

`export NODE_OPTIONS="--openssl-legacy-provider";`
